# -*- coding: utf-8 -*-
"""Ejercicio 8.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11d4tKphHuJhUdwUcl0K5WprC5fjLwbSa
"""

#Ejercicio 8.2:

def calcular_resultados():
    try:
        notas = [float(entry.get()) for entry in entradas]
        promedio = sum(notas) / len(notas)
        desviacion = statistics.stdev(notas)
        mayor = max(notas)
        menor = min(notas)

        resultado_texto = (
            f"Promedio: {promedio:.2f}\n"
            f"Desviación estándar: {desviacion:.2f}\n"
            f"Mayor nota: {mayor}\n"
            f"Menor nota: {menor}"
        )
        resultado_label.config(text=resultado_texto)

    except ValueError:
        messagebox.showerror("Error", "Por favor ingresa solo números válidos.")

# Ventana principal
ventana = tk.Tk()
ventana.title("Notas de estudiante")
ventana.geometry("300x400")

titulo = tk.Label(ventana, text="Ingrese cinco notas:", font=("Arial", 12))
titulo.pack(pady=10)

entradas = []
for i in range(5):
    entrada = tk.Entry(ventana)
    entrada.pack(pady=5)
    entradas.append(entrada)

boton = tk.Button(ventana, text="Calcular resultados", command=calcular_resultados)
boton.pack(pady=10)

resultado_label = tk.Label(ventana, text="", font=("Arial", 10), justify="left")
resultado_label.pack(pady=20)

ventana.mainloop()